import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Lora } from "next/font/google";
import ToastProvider from '@/components/ToastProvider';
import { SessionProvider } from "next-auth/react"
import { auth } from "@/auth";
import { redirect } from "next/navigation";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth()

  // if(!session) redirect('/sign-in')

  return (
    <html lang="en" suppressHydrationWarning>
      <SessionProvider session={session}>
        <body
          className={`${montserrat.variable} ${lora.variable} antialiased`}
        >
          <ToastProvider />
          {children}
        </body>
      </SessionProvider>
    </html>
  );
}
